-- Substitui a primeira versão do RAG (extensao_rag_produtos_embeddings.sql,
-- HTTP manual pra OpenRouter) pelo node nativo do n8n
-- (@n8n/n8n-nodes-langchain.vectorStoreSupabase) -- usuário apontou que dava
-- pra usar o node nativo em vez de HTTP Request manual + sub-workflow, e tinha
-- razão: menos peça móvel, menos chance de bug de wiring. Trocado em 22/08/2026.
--
-- Consequência de usar o node nativo: ele segue o contrato padrão do
-- LangChain/Supabase quickstart (tabela com content/metadata/embedding + função
-- match_<nome>(query_embedding, match_count, filter) retornando
-- id/content/metadata/similarity) -- não é mais um schema livre feito à mão.
--
-- Também trocou o provedor de embedding: o node nativo de embeddings do
-- OpenRouter não existe no n8n (só teria via credential openAiApi com Base URL
-- customizada, que exigiria criar uma credential nova com a chave em mãos --
-- bloqueio que não existia pro Google Gemini, cuja credential
-- ("Google Gemini(PaLM) Api account") já estava cadastrada no n8n). Por isso
-- este RAG usa Gemini (`models/gemini-embedding-001`, 768 dims) em vez de
-- OpenRouter/OpenAI. Pode trocar para OpenRouter depois se/quando existir uma
-- credential openAiApi com Base URL apontando pra ele.
--
-- Aplicado em produção via mcp__supabase__apply_migration (nome
-- "rag_produtos_vectorstore_nativo") em 22/08/2026.

drop function if exists buscar_produtos_similares(vector, int, float);
drop table if exists produtos_embeddings;

create table produtos_documentos (
  id bigint generated by default as identity primary key,
  produto_id uuid not null unique references produtos(id) on delete cascade,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(768)
);

comment on table produtos_documentos is
  'Vector store do catálogo pro node nativo @n8n/n8n-nodes-langchain.vectorStoreSupabase (workflow "Agente vendedor", tool "Busca Inteligente"). content = texto embedado (nome + aliases + preço); metadata = {produto_id, nome, preco}. Embedding via Gemini (768 dims) -- ver node "Embeddings Google Gemini" no mesmo workflow. Ingestão pela branch manual "Rodar Ingestão de Embeddings" no mesmo workflow.';

create index produtos_documentos_embedding_idx
  on produtos_documentos
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 10);

alter table produtos_documentos enable row level security;

create policy "operadores leem produtos_documentos"
  on produtos_documentos for select
  to authenticated
  using (eh_operador_ativo());

revoke all on produtos_documentos from anon, public;
grant select on produtos_documentos to authenticated, service_role;
grant insert, update, delete on produtos_documentos to service_role;

-- Assinatura exigida pelo node nativo (Query Name = match_produtos_documentos
-- nas options do node, tanto no modo "Insert" quanto no "Retrieve"):
-- match_documents(query_embedding, match_count, filter) -> id/content/metadata/similarity.
create or replace function match_produtos_documentos(
  query_embedding vector(768),
  match_count int default null,
  filter jsonb default '{}'
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  return query
  select
    pd.id,
    pd.content,
    pd.metadata,
    1 - (pd.embedding <=> query_embedding) as similarity
  from produtos_documentos pd
  where pd.metadata @> filter
  order by pd.embedding <=> query_embedding
  limit match_count;
end;
$function$;

revoke execute on function match_produtos_documentos(vector, int, jsonb) from anon, public;
grant execute on function match_produtos_documentos(vector, int, jsonb) to authenticated, service_role;
